# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd
import PCAFactorAnalysis as pca

# Read a matrix from a file
# Find Eigenvalues / Eigenvectors
# Sort the values, select 2 eigenvectors associated with the biggest eigenvalues
# Norm the selected eigenvectors
# Project the original matrix in the plan generated by the 2 eigenVectors
# Plot (with some formatting options), print biggest eigenvalues, normed eigenvectors, compute loss of information

def GenerateNRandTestData(shape=(100, 5)):
    """
    Generate a random matrix (with normally distributed values) of the passed shape.
    """
    testData = pd.DataFrame(np.random.randn(shape[0], shape[1]))
    return testData

def GenerateClusterDataSet(shape=(400, 5)):
    """
    Generate a random matrix with 1 to 4 clusters more or less distinguishable
    """
    multiple = shape[0]//4
    testData = np.random.randn(shape[0], shape[1])
    testData[0:(multiple-1),:] = 2* np.random.randn(multiple-1, shape[1]) +8
    testData[multiple:((2*multiple)-1),:] = -4 * np.random.randn(multiple-1, shape[1]) -16
    testData[(2*multiple):((3*multiple)-1), :] = -1 * np.random.randn(multiple-1, shape[1]) -2
    return pd.DataFrame(testData)

def SaveTestData(testData, path='Example/testSet.csv'):
    """
    Returns True if the data passed were successfully saved in the Example folder. Else, it returns False.
    """
    try:
        testData.to_csv(path, mode='w+', sep=',', index = False, header=False)
    except Exception as e:
        print("Could not save test data.")
        print(e)
        return False
    return True

def ReadTestData(path='Example/testSet.csv'):
    try:
        testData = np.genfromtxt(path, delimiter=',')
    except Exception as e:
        print(e)
        return 0
    return testData
    
    
if __name__ == "__main__":
    
    #testData = GenerateNRandTestData()
    testData = GenerateClusterDataSet(shape=(1000, 15))
    SaveTestData(testData)
    
    projectedTestData = pca.Get2DProjectedMatrix(testData)
    SaveTestData(pd.DataFrame(projectedTestData), path='Example/projectedTestSet.csv')
    
    
    pca.Plot2DMatrix(projectedTestData)
    print(pca.GetInformationLoss(testData))
    
    